name: KiCad PCB Check

on:
  pull_request:
    paths:
      - '**/*.kicad_pcb'
    types: [opened, synchronize, reopened, assigned]

jobs:
  check-pcb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Install KiCad tools (if needed)
      - name: Install KiCad
      - id: kicad-inst
        run: |
          sudo add-apt-repository -y ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt install --install-recommends -y kicad
      
      # Install Python & Deps
      - name: Install UV, Python, Dependencies
        id: python-deps
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv python install 3.12

      - name: Configure Environment Variables
        id: env-cfg
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_REPO=${{ github.repository }}
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Run Python Checks
        id: run-tests
        run: |
          cd ci 
          uv sync 
          uv run python main.py
